name: Deploy to Dokku - stage

on:
  push:
    branches: [stage]

env:
  DOKKU_HOST: 'vacations.rip'
  DOKKU_APP_NAME: 'stage-prova'
  DOKKU_REMOTE_BRANCH: 'stage'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy
        uses: woudsma/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_KEY }}
          dokku-host: ${{ env.DOKKU_HOST }}
          app-name: ${{ env.DOKKU_APP_NAME }}
          remote-branch: ${{ env.DOKKU_REMOTE_BRANCH }}
